# Generated by Django 5.2.5 on 2025-09-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklymenu',
            name='dinner_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('ended', 'Yakunlangan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='lunch_status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('ended', 'Yakunlangan')], default='pending', max_length=20),
        ),
    ]
