# Generated by Django 5.2.5 on 2025-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='So‘rovnoma tugash vaqti'),
        ),
        migrations.AddField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='So‘rovnoma boshlanish vaqti'),
        ),
        migrations.AddField(
            model_name='meal',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('ended', 'Tugagan')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Rasm'),
        ),
    ]
