# Generated by Django 5.2.5 on 2025-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_weeklymenu_dinner_status_weeklymenu_lunch_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklymenu',
            old_name='lunch',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='weeklymenu',
            old_name='dinner_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='weeklymenu',
            name='lunch_status',
        ),
        migrations.AddField(
            model_name='weeklymenu',
            name='meal_type',
            field=models.CharField(choices=[('lunch', 'Abed'), ('dinner', 'Kechki')], default='lunch', max_length=20),
            preserve_default=False,
        ),
    ]
