# Generated by Django 5.2.5 on 2025-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_meal_end_time_meal_start_time_meal_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='end_time',
            field=models.TimeField(verbose_name='So‘rovnoma tugash vaqti'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='start_time',
            field=models.TimeField(verbose_name='So‘rovnoma boshlanish vaqti'),
        ),
    ]
