# Generated by Django 5.2.5 on 2025-09-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_lunch_weeklymenu_meal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealresponse',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='apps.weeklymenu'),
        ),
    ]
