# Generated by Django 5.2.5 on 2025-09-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_mealresponse_meal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealresponse',
            old_name='meal',
            new_name='menu',
        ),
        migrations.AlterUniqueTogether(
            name='mealresponse',
            unique_together={('user', 'menu')},
        ),
    ]
